# Generated by Django 4.1.7 on 2023-02-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, default=None, upload_to="pics"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stih",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Stih title"
                    ),
                ),
                (
                    "epigraph",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Epigraph"
                    ),
                ),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "createdAt",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Created At"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stihs",
                        to="api.author",
                    ),
                ),
            ],
        ),
    ]
