# Generated by Django 4.1.7 on 2023-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
