# Generated by Django 4.1.7 on 2023-05-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_author_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.TextField(blank=True, default=" "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stih",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.author",
            ),
        ),
    ]
