# Generated by Django 4.1.7 on 2023-06-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_author_description_alter_stih_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="stih",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
