# Generated by Django 4.1.7 on 2023-06-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_stih_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stih",
            name="epigraph",
            field=models.TextField(blank=True, verbose_name="Epigraph"),
        ),
    ]
