# Generated by Django 5.0.6 on 2025-08-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_stih_epigraph"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Tag title")),
            ],
        ),
        migrations.AddField(
            model_name="stih",
            name="tags",
            field=models.ManyToManyField(to="api.tags"),
        ),
    ]
