# Generated by Django 5.0.6 on 2025-08-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_tags_stih_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stih",
            name="tags",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="api.tags"
            ),
        ),
    ]
