# Generated by Django 5.0.6 on 2025-10-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_stih_tags"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
        )
    ]
